before:
  hooks:
    - go mod download
builds:
  -
    id: batman
    main: ./cmd/main.go
    binary: batman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin_macOS
      amd64: x86_64
changelog:
  # skip changelog generation for now
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
