before:
  hooks:
    - go mod download
builds:
  -
    id: batman
    dir: .
    main: ./main.go
    binary: batman
    env:
      - CGO_ENABLED=0
      - VERSION=$(git describe --tags --abbrev=0)
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin_macOS
      amd64: x86_64
changelog:
  # skip changelog generation for now
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
