on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

name: CI

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get deps
        run: |
          go mod download

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test

      - name: Build
        run: make build
